# Generated by Django 4.2 on 2023-07-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templatesapi", "0002_category_userprofile_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
