# Generated by Django 4.2 on 2023-07-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templatesapi", "0003_alter_userprofile_email_alter_userprofile_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="old_password",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
