# Generated by Django 4.2 on 2023-07-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "templatesapi",
            "0006_remove_userprofile_created_at_userprofile_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="is_free",
            field=models.BooleanField(default=True),
        ),
    ]
